apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deployment
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: products 
  template:
    metadata:
      labels:
        app: products 
    spec:
      containers:
        - name: products 
          image: axxshique/micro_product:{{tag}}
          env:
            - name: MONGO_URI
              value: 'mongodb+srv://cmt:admin123@cluster0.yjsmx.mongodb.net/cmt_testing123?retryWrites=true&w=majority'
            - name: JWT_KEY
              value: 'high-secret-1133'
