apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deployment
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: products 
  template:
    metadata:
      labels:
        app: products 
    spec:
      containers:
        - name: products 
          image: axxshique/micro_products
          env:
            - name: MONGO_URI
              value: 'mongodb+srv://cmt:admin123@cluster0.yjsmx.mongodb.net/cmt_testing123?retryWrites=true&w=majority'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: products-service
# spec:
#   type: ClusterIP
#   selector:
#     app: products 
#   ports:
#     - name: products 
#       protocol: TCP
#       port: 8081
#       targetPort: 8081