apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: products-deployment
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: products
status:
  loadBalancer: {}