name: Docker Build Deploy

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: run shell script
      run: echo commit hash is ${{ github.sha }}
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_UNM }}
        password: ${{ secrets.DOCKER_TKN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_UNM }}/micro_product:${{ github.sha }}
    - name: Update config files in k8s
      run: sed -i.bak 's/{{tag}}/${{ github.sha }}/g' ./k8s/products-deployment.yaml && rm k8s/*.bak
    - uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: apply -f ./k8s