name: Docker Build Deploy

on:
  push:
    branches: [ master ]

env:
  PROJECT_ID: ${{ secrets.GCLOUD_PROJUCT_NAME }}
  GCLOUD_CLUSTER: product-management
  GCLOD_ZONE: us-central1
  DEPLOYMENT_NAME: products-deployment
  DEPLOYMENT_NAME_1: products-mongo-deployment

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: run shell script
      run: echo commit hash is ${{ github.sha }}
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_UNM }}
        password: ${{ secrets.DOCKER_TKN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_UNM }}/micro_product:${{ github.sha }}
    - name: Update config files in k8s
      run: sed -i.bak 's/{{tag}}/${{ github.sha }}/g' ./k8s/products-deployment.yaml && rm k8s/*.bak
    - id: "authentication"
      uses: "google-github-actions/auth@v0"
      with:
        credentials_json: "${{ secrets.GCLOUD_CREDENTIALS }}"
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
    - name: "Using Gcloud CLI"
      run: "gcloud info"
    - run: |-
        gcloud container clusters get-credentials "$GCLOUD_CLUSTER" --zone "$GCLOD_ZONE"
    - name: Deploy
      run: |-
        kubectl apply -f k8s/products-deployment.yaml
        kubectl apply -f k8s/products-mongo-deployment.yaml
        kubectl rollout status deployment/$DEPLOYMENT_NAME
        kubectl rollout status deployment/$DEPLOYMENT_NAME_1
        kubectl get services -o wide